### ISSUE TITLE
Make tuleap users & credentials configurable

### ISSUE THREAD

**Issue by jprezaj** [DigitalOnUs/projector#1]
Make tuleap credentials configurable either in `docker-compose.yml` or by `Dockerfile`.

**Comment by mrrusof** [comment]
Requirements:

1. Pass in [`boot-install.sh:37`](https://github.com/DigitalOnUs/projector/blob/master/tuleap/boot-install.sh#L37) credentials for the following accounts:
    1. Mysql user (root)
    2. Codendiadm unix & DB (codendiadm)
    3. Libnss-mysql DB user (dbauthuser)
    4. Site admin password (admin):
2. You will find option names for each password in the [option parsing code of Tuleap's `setup.sh`](https://github.com/Enalean/tuleap/blob/e06359339d4d5d00092217d316d8c9ff946e94e5/tools/setup.sh#L831).
3. Credentials come from corresponding environment variables and have defaults. Take as example [`boot-install.sh:40`](https://github.com/DigitalOnUs/projector/blob/master/tuleap/boot-install.sh#L40)
4. ~Set all passwords to `admin` in `docker-compose.yml`.~ Only set root and site admin passwords in `docker-compose.yml`.
